[package]
name = "rudder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-tree = "0.2.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
rusqlite = "0.28.0"
futures = "0.3"
headers = "0.3"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.3.0", features = ["fs", "trace"] }
axum = { version = "0.5.16", features = ["ws", "headers"] }
# axum = { git = "https://github.com/tokio-rs/axum", branch = "main", features = ["ws", "headers"]  }
clap = { version = "4.0.13", features = ["derive"] }
