[package]
name = "rudder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
thiserror = "1.0.37"
color-eyre = "0.6.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-tree = "0.2.1"
once_cell = "1.15.0"
elsa = "1.7.0"
nom = "7.1.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
rusqlite = "0.28.0"
futures = "0.3"
clap = { version = "4.0.13", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.3.0", features = ["fs", "trace"] }
headers = "0.3"
axum = { version = "0.5.16", features = ["ws", "headers", "json"] }
axum-typed-websockets = "0.4.0"
markdown-gen = "1.2.1"
erased-serde = "0.3.23"
nanoid = "0.4.0"
treediff = { version = "4.0.2", features = ["with-serde-json"] }
color-backtrace = "0.5.1"
rustyline = "10.0.0"
# axum = { git = "https://github.com/tokio-rs/axum", branch = "main", features = ["ws", "headers", "json"]  }
